### ISSUE TITLE
Add support for The Ocean

### ISSUE THREAD

**Issue by stefanmendoza** [grahamperich/ethereum-dex-prices-service#1]
[The Ocean](https://theocean.trade) is a [0x relayer](https://0x.org/wiki#List-of-Projects-Using-0x-Protocol). Their API allows for retrieval of orderbook info behind unauthenticated, rate-limited endpoints: https://docs.theocean.trade/#rate-limit

A client is also provided if you want some wrapper functions for interacting with the API:
https://docs.theocean.trade/#order-book-3

Based on some of the other examples, I think these are the two endpoints that will be useful:
- https://docs.theocean.trade/#token-pairs-2
- https://docs.theocean.trade/#order-book-3

**Comment by stefanmendoza** [comment]
```
Identity verification is required to prevent fraud and keep our community safe. It is also necessary part to expanding our marketplace to tokenized assets in near future.

To create an account, you'll need to sign up with your e-mail and walk through our verification process. If everything's in order, you'll be approved to trade in just minutes.
```

So it looks like their may be a KYC component to this relayer as the first step in their setup guide.

**Comment by grahamperich** [comment]
I don't think it would make sense to add The Ocean at this time. The primary goal for this tool is to compare data among classic decentralized exchanges that allow you to trade with just an Ethereum address. I also didn't add Paradex for this reason.

Right now there are really three different types of crypto exchanges: 
1. Custodial order matching exchanges. These are the traditional custodial exchanges that require you to register for an account and deposit your assets. Examples: Coinbase, Binance, Bitfinex

2. True Permisionless Decentralized Exchanges. The UI front ends are run by centralized entities and so there may be some blocking of tokens and geographic regions, but at the protocol level anyone can trade with just an Ethereum address. Examplse: AirSwap, Kyber, Bancor, Uniswap, ForkDelta

3. Hybrid exchanges. These exchanges generally use the blockchain to enable non-custodial trade, but they still perform centralized order matching and usually require registration and identity verification. Examples: Paradex, The Ocean, eventually IDEX once they add KYC.

My idea for this service is to aggregate data from all of those in group 2.
