### ISSUE TITLE
UnhandledPromiseRejectionWarning: Could not connect to socket

### ISSUE THREAD

**Issue by calbertuk** [grahamperich/ethereum-dex-prices-service#17]
Getting this since this morning:

`UnhandledPromiseRejectionWarning: Could not connect to socket
`

When running

`node entrypoints/cli.js buy 1 MKR
`
Worked fine yesterday.

**Comment by grahamperich** [comment]
Can you provide as much data as possible about the error @calbertuk ?

Specifically, the full call stack of the error with line numbers if they're included. 

Also your machine, environment, etc..

Thanks!

**Comment by calbertuk** [comment]
ethereum-dex-prices-service# node entrypoints/cli.js buy 1 MKR
Working...
(node:24087) UnhandledPromiseRejectionWarning: Could not connect to socket
(node:24087) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24087) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Ubuntu 18.04
Node v8.11.4


Worked fine yesterday. Pulled latest repo and ran yarn install and still getting the same error.

**Comment by calbertuk** [comment]
Clone the virtual machine and it's working fine now. Very bizarre but unrelated to your great tool!

**Comment by calbertuk** [comment]
I just started receiving the error again. Seems to be Airswap is causing the issue. I believe I must be making too many requests (four a minute) and the IP is getting throttled.

**Comment by calbertuk** [comment]
Would be great if there could be a workaround.

**Comment by grahamperich** [comment]
Yeah it sounds like AirSwap is rate limiting the WS connections. I'll add some handling for this type of exception and make it so that the AirSwap class returns a descriptive error message about what's happening in the `results` object. Thanks for the bug report @calbertuk

**Comment by grahamperich** [comment]
resolvled by commit https://github.com/grahamperich/ethereum-dex-prices-service/commit/33adfc9e8ad2a65ceac153784039e6eabed04e93

@calbertuk
