### ISSUE TITLE
DEXes APIs

### ISSUE THREAD

**Issue by eliooses** [grahamperich/ethereum-dex-prices-service#20]
Hi there!,

@grahamperich my name is Elio and I am the admin of **inDEX** (https://github.com/distribuyed/index). inDEX is a comprehensive list of decentralized exchanges of cryptocurrencies, tokens, derivatives and futures, their protocols, and other resources.

I do not have the time neither skills to collaborate as much as I would like with your project, but if it is helpful, I can help you by indicating DEXes with API that you can use for your project.

For example, the last I found:

| DEX | URL | API |
|:-------------:|:-------------:|:-------------:|
| TOKENMON | https://tokenmom.com | https://docs.tokenmom.com/#introduction |

Thanks a lot in advance and congratulations for the project!

**Comment by grahamperich** [comment]
hey @eliooses thanks for making me aware of this project 😄

I'll start watching it!
