### ISSUE TITLE
Add support for EthFinex

### ISSUE THREAD

**Issue by grahamperich** [grahamperich/ethereum-dex-prices-service#3]
EthFinex has a trustless API that could easily be implemented in this library https://trustless.ethfinex.com

Requirements:
- Create an EthFinex class that inherits from the `OrderBookExchange` class and implements the EthFinex API correctly
- It should be called as part of the `main()` routine

**Comment by stefanmendoza** [comment]
I'll start digging into this one!

**Comment by stefanmendoza** [comment]
Base URL will be: `https://api.ethfinex.com/trustless/v1/`

Documentation can be found here: https://ethfinex.docs.apiary.io/#introduction/public-endpoints

For public endpoints, we can just use the Bitfinex API documentation: https://docs.bitfinex.com/v1/docs/rest-general

**Comment by sterlu** [comment]
Hey @stefanmendoza, I'm glad to see you working on this. I've been working on EFX Trustless development so if I can help in any way let me know. :)
