### ISSUE TITLE
Discussion: Addition of unit tests and/or integration tests

### ISSUE THREAD

**Issue by stefanmendoza** [grahamperich/ethereum-dex-prices-service#9]
I'm thinking it would be valuable to have unit tests per exchange and possibly integration tests to assert some of the calculation logic / catch an API non-passively changing? Thoughts?

**Comment by saturn-network** [comment]
While writing #8 I ended up debugging some typos that could have easily be avoided if the project was using TypeScript (on a somewhat related note)

**Comment by grahamperich** [comment]
Yeah, unit tests would certainly be nice to have. The highest value test would probably be testing the `computePrice()` method for all the exchange classes. It would also make contributing easier. I would certainly support adding a library like https://jestjs.io/ to the project. 

I'm a fan of TypeScript as well, but a full TypeScript rewrite is probably out of reach at this point. If someone actually did it, I would happily merge it. But it's a big ask, and the fact that all of the exchange classes are totally encapsulated means that types shouldn't be _too_ hard to reason about.

**Comment by stefanmendoza** [comment]
I started digging into the unit tests last night. Aiming to have a PR out in a couple days. 👍

**Comment by stefanmendoza** [comment]
Got the first PR out for unit tests. Once this pattern / config is +1'd, I can star ton the other exchanges.

https://github.com/grahamperich/ethereum-dex-prices-service/pull/15

**Comment by grahamperich** [comment]
resolved by #15
